<?php

declare(strict_types=1);

/**
 * Metadata cleaner / normalizer for K/3 Cloud entity + field exports.
 *
 * Reads a (possibly messy, 二开-contaminated) export of entities + fields and
 * produces clean, grouped artifacts under .docs/, splitting genuine
 * secondary-development ("二开") custom fields from standard platform fields.
 *
 * Usage:
 *   php tools/build-metadata.php [entity.json] [field.json] [outDir]
 * Defaults point at the known export location and write to .docs/ next to this repo.
 *
 * Classification rule (deliberately narrow to avoid false positives):
 *   a field is treated as CUSTOM when kingdee_name matches  ^F_[A-Za-z0-9]{2,4}_
 *   e.g. F_PAEZ_lixi, F_PEYC_Decimal, F_PDQP_PrintTimes.
 * Standard platform sub-fields that merely contain "_" (FBillAmount_LC,
 * FEntity_Link_FFlowId, FEntity_FENTRYID, FMaterialID_Sal, ...) are NOT custom
 * and are kept.
 */

$inEntity = $argv[1] ?? 'E:/Dev/rebuild/.docs/kingdee_entity.json';
$inField  = $argv[2] ?? 'E:/Dev/rebuild/.docs/kingdee_field.json';
$outDir   = $argv[3] ?? dirname(__DIR__) . '/.docs';

if (!is_dir($outDir) && !mkdir($outDir, 0777, true) && !is_dir($outDir)) {
    fwrite(STDERR, "cannot create out dir: $outDir\n");
    exit(1);
}

$entities = read_json($inEntity);
$fields   = read_json($inField);

/** entity_id => entity meta */
$entById = [];
foreach ($entities as $e) {
    $entById[(int) $e['id']] = $e;
}

/**
 * index[entity_id][segment_code][field_key] => ['key','title','length']
 * custom[entity_id][segment_code][field_key] => same shape
 * plus bookkeeping for the report.
 */
$standard = [];
$custom   = [];
$seenCustomCodes = [];
$anomalies = [];
$dupes = 0;
$unknownEntityRefs = [];

foreach ($fields as $f) {
    $eid  = (int) ($f['kingdee_entity_id'] ?? 0);
    $key  = trim((string) ($f['kingdee_name'] ?? ''));
    $seg  = trim((string) ($f['cate_code'] ?? '')) ?: '(unsegmented)';
    $segName = trim((string) ($f['cate_name'] ?? ''));
    $title = trim((string) ($f['title'] ?? ''));
    $len   = (string) ($f['length'] ?? '');

    if (!isset($entById[$eid])) {
        $unknownEntityRefs[$eid] = ($unknownEntityRefs[$eid] ?? 0) + 1;
    }
    if ($key === '' || !preg_match('/^[A-Za-z_]/', $key)) {
        $anomalies[] = ['entity_id' => $eid, 'name' => $key];
    }

    $isCustom = (bool) preg_match('/^F_[A-Za-z0-9]{2,4}_/', $key);
    if ($isCustom && preg_match('/^F_([A-Za-z0-9]{2,4})_/', $key, $m)) {
        $seenCustomCodes[$m[1]] = ($seenCustomCodes[$m[1]] ?? 0) + 1;
    }

    $bucket = $isCustom ? 'custom' : 'standard';
    $slot = $$bucket;
    if (isset($slot[$eid][$seg][$key])) {
        $dupes++;
        continue; // keep first occurrence; drop exact duplicates within a segment
    }
    $slot[$eid][$seg][$key] = ['key' => $key, 'title' => $title, 'length' => $len];
    $slot[$eid]['_seg_names'][$seg] = $segName;
    $$bucket = $slot;
}

$standardOut = build_entities($standard, $entById);
$customOut   = build_entities($custom, $entById);

write_json("$outDir/kingdee_entity.json", array_map(
    static fn ($e) => [
        'entity_code' => $e['entity_code'],
        'entity_name' => $e['entity_name'],
        'module'      => $e['entity_description'],
    ],
    $entities
));
write_json("$outDir/kingdee_field.standard.json", $standardOut);
write_json("$outDir/kingdee_field.custom.json", $customOut);

// ---- report ----
$stdFieldCount  = count_flat($standardOut);
$custFieldCount = count_flat($customOut);

$lines = [];
$lines[] = '# K/3 Cloud metadata — clean export';
$lines[] = '';
$lines[] = 'Generated by `tools/build-metadata.php` from:';
$lines[] = "- entities: `$inEntity`";
$lines[] = "- fields:   `$inField`";
$lines[] = '';
$lines[] = '## Summary';
$lines[] = '';
$lines[] = '| metric | value |';
$lines[] = '|---|---|';
$lines[] = '| entities (source) | ' . count($entities) . ' |';
$lines[] = '| fields (source rows) | ' . count($fields) . ' |';
$lines[] = '| standard fields (clean) | ' . $stdFieldCount . ' |';
$lines[] = '| custom 二开 fields (split out) | ' . $custFieldCount . ' |';
$lines[] = '| exact duplicates dropped | ' . $dupes . ' |';
$lines[] = '| anomalies (non-letter field keys) | ' . count($anomalies) . ' |';
$lines[] = '';
$lines[] = '## Files';
$lines[] = '- `kingdee_entity.json` — normalized `{entity_code, entity_name, module}`.';
$lines[] = '- `kingdee_field.standard.json` — standard fields grouped by entity → segment.';
$lines[] = '- `kingdee_field.custom.json` — 二开 fields grouped the same way (kept, not deleted).';
$lines[] = '';
$lines[] = '## Classification rule';
$lines[] = '';
$lines[] = 'A field is **custom** iff `kingdee_name` matches `^F_[A-Za-z0-9]{2,4}_`';
$lines[] = '(e.g. `F_PAEZ_lixi`, `F_PEYC_Decimal`). Standard sub-fields that merely';
$lines[] = 'contain `_` (`FBillAmount_LC`, `FEntity_Link_FFlowId`, `FEntity_FENTRYID`,';
$lines[] = '`FMaterialID_Sal`) are **kept as standard**.';
$lines[] = '';
if ($seenCustomCodes !== []) {
    arsort($seenCustomCodes);
    $lines[] = '## Detected 二开 business-group codes (please confirm these are yours)';
    $lines[] = '';
    foreach ($seenCustomCodes as $code => $n) {
        $lines[] = "- `F_{$code}_*` — {$n} field(s)";
    }
    $lines[] = '';
}
if ($unknownEntityRefs !== []) {
    $lines[] = '## WARNING: fields referencing unknown entity ids';
    foreach ($unknownEntityRefs as $eid => $n) {
        $lines[] = "- entity_id $eid → $n field(s)";
    }
    $lines[] = '';
}
if ($anomalies !== []) {
    $lines[] = '## Anomalous field keys (review)';
    foreach (array_slice($anomalies, 0, 50) as $a) {
        $lines[] = "- entity_id {$a['entity_id']}: `" . ($a['name'] === '' ? '(empty)' : $a['name']) . '`';
    }
    $lines[] = '';
}
$lines[] = '## Per-entity field counts (standard / custom)';
$lines[] = '';
$lines[] = '| entity_code | entity_name | standard | custom |';
$lines[] = '|---|---|---:|---:|';
$stdByCode = array_column($standardOut, null, 'entity_code');
$cusByCode = array_column($customOut, null, 'entity_code');
foreach ($entities as $e) {
    $code = $e['entity_code'];
    $s = count_fields($stdByCode[$code] ?? []);
    $c = count_fields($cusByCode[$code] ?? []);
    $lines[] = "| {$code} | {$e['entity_name']} | $s | $c |";
}

file_put_contents("$outDir/kingdee_metadata_report.md", implode("\n", $lines) . "\n");

echo "OK\n";
echo "entities=" . count($entities)
    . " standard=$stdFieldCount custom=$custFieldCount dupes=$dupes anomalies=" . count($anomalies) . "\n";
echo "wrote:\n  $outDir/kingdee_entity.json\n  $outDir/kingdee_field.standard.json\n  $outDir/kingdee_field.custom.json\n  $outDir/kingdee_metadata_report.md\n";

/* ---------------- helpers ---------------- */

function read_json(string $path): array
{
    if (!is_file($path)) {
        fwrite(STDERR, "input not found: $path\n");
        exit(1);
    }
    $data = json_decode((string) file_get_contents($path), true);
    if (!is_array($data)) {
        fwrite(STDERR, "invalid JSON: $path\n");
        exit(1);
    }
    return $data;
}

function write_json(string $path, mixed $data): void
{
    file_put_contents($path, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n");
}

/** Turn an index[entity_id] into a sorted list of entity blocks with segments. */
function build_entities(array $index, array $entById): array
{
    $out = [];
    foreach ($index as $eid => $segs) {
        $segNames = $segs['_seg_names'] ?? [];
        unset($segs['_seg_names']);
        $segments = [];
        foreach ($segs as $code => $fields) {
            $list = array_values($fields);
            usort($list, static fn ($a, $b) => strcmp($a['key'], $b['key']));
            $segments[] = [
                'code'   => $code,
                'name'   => $segNames[$code] ?? '',
                'fields' => $list,
            ];
        }
        usort($segments, static fn ($a, $b) => strcmp($a['code'], $b['code']));
        $ent = $entById[$eid] ?? [];
        $out[] = [
            'entity_id'   => $eid,
            'entity_code' => $ent['entity_code'] ?? ('UNKNOWN_' . $eid),
            'entity_name' => $ent['entity_name'] ?? '',
            'module'      => $ent['entity_description'] ?? '',
            'segments'    => $segments,
        ];
    }
    usort($out, static fn ($a, $b) => strcmp($a['entity_code'], $b['entity_code']));
    return $out;
}

function count_fields(array $entityBlock): int
{
    $n = 0;
    foreach ($entityBlock['segments'] ?? [] as $seg) {
        $n += count($seg['fields']);
    }
    return $n;
}

function count_flat(array $entityBlocks): int
{
    $n = 0;
    foreach ($entityBlocks as $b) {
        $n += count_fields($b);
    }
    return $n;
}
