<?php

declare(strict_types=1);

/**
 * K/3 Cloud 实体 + 字段导出的清洗 / 规范化工具。
 *
 * 读取一份（可能杂乱、混有二开字段的）实体 + 字段导出，在 .docs/ 下产出干净、分组好的
 * 产物，并把真正的二次开发（"二开"）自定义字段与平台标准字段区分开。
 *
 * 用法：
 *   php tools/build-metadata.php [entity.json] [field.json] [outDir] [--scaffold] [options]
 *
 * 位置参数默认指向已知的导出位置 + .docs/。带 --scaffold 时，还会额外把"每个实体的起始
 * PHP 类"（FORM_ID + 字段名常量 + 分录 helper）生成到一个被 git 忽略的 scaffold 目录——
 * 供开发者拷进自己工程再编辑。这里生成的任何东西都不是白名单。
 *
 * 选项（配合 --scaffold）：
 *   --namespace=App\K3Cloud\Entities   生成文件的命名空间
 *   --scaffold-out=<dir>               输出目录（默认 <outDir>/scaffold）
 *   --with-custom                      也把二开字段作为常量生成
 *
 * 分类规则（有意收窄以避免误判）：
 *   当 kingdee_name 匹配 ^F_[A-Za-z0-9]{2,4}_ 时，字段视为 CUSTOM，
 *   例如 F_PAEZ_lixi、F_PEYC_Decimal、F_PDQP_PrintTimes。
 *   仅仅是"含下划线"的标准平台子字段（FBillAmount_LC、FEntity_Link_FFlowId、
 *   FEntity_FENTRYID、FMaterialID_Sal……）不是二开，予以保留。
 */

$positional = [];
$flags = [];
foreach (array_slice($argv, 1) as $arg) {
    if (str_starts_with($arg, '--')) {
        [$k, $v] = array_pad(explode('=', substr($arg, 2), 2), 2, null);
        $flags[$k] = $v ?? true;
    } else {
        $positional[] = $arg;
    }
}

$inEntity = $positional[0] ?? 'E:/Dev/rebuild/.docs/kingdee_entity.json';
$inField  = $positional[1] ?? 'E:/Dev/rebuild/.docs/kingdee_field.json';
$outDir   = $positional[2] ?? dirname(__DIR__) . '/.docs';

$scaffold     = isset($flags['scaffold']);
$scaffoldNs   = (string) ($flags['namespace'] ?? 'App\\K3Cloud\\Entities');
$scaffoldOut  = (string) ($flags['scaffold-out'] ?? $outDir . '/scaffold');
$withCustom   = isset($flags['with-custom']);

if (!is_dir($outDir) && !mkdir($outDir, 0777, true) && !is_dir($outDir)) {
    fwrite(STDERR, "cannot create out dir: $outDir\n");
    exit(1);
}

$entities = read_json($inEntity);
$fields   = read_json($inField);

/** entity_id => 实体元信息 */
$entById = [];
foreach ($entities as $e) {
    $entById[(int) $e['id']] = $e;
}

/**
 * index[entity_id][segment_code][field_key] => ['key','title','length']
 * custom[entity_id][segment_code][field_key] => 同结构
 * 另外为报告做一些簿记。
 */
$standard = [];
$custom   = [];
$seenCustomCodes = [];
$anomalies = [];
$dupes = 0;
$unknownEntityRefs = [];

foreach ($fields as $f) {
    $eid  = (int) ($f['kingdee_entity_id'] ?? 0);
    $key  = trim((string) ($f['kingdee_name'] ?? ''));
    $seg  = trim((string) ($f['cate_code'] ?? '')) ?: '(unsegmented)';
    $segName = trim((string) ($f['cate_name'] ?? ''));
    $title = trim((string) ($f['title'] ?? ''));
    $len   = (string) ($f['length'] ?? '');

    if (!isset($entById[$eid])) {
        $unknownEntityRefs[$eid] = ($unknownEntityRefs[$eid] ?? 0) + 1;
    }
    if ($key === '' || !preg_match('/^[A-Za-z_]/', $key)) {
        $anomalies[] = ['entity_id' => $eid, 'name' => $key];
    }

    $isCustom = (bool) preg_match('/^F_[A-Za-z0-9]{2,4}_/', $key);
    if ($isCustom && preg_match('/^F_([A-Za-z0-9]{2,4})_/', $key, $m)) {
        $seenCustomCodes[$m[1]] = ($seenCustomCodes[$m[1]] ?? 0) + 1;
    }

    $bucket = $isCustom ? 'custom' : 'standard';
    $slot = $$bucket;
    if (isset($slot[$eid][$seg][$key])) {
        $dupes++;
        continue; // 保留首次出现；丢弃同一分段内的完全重复项
    }
    $slot[$eid][$seg][$key] = ['key' => $key, 'title' => $title, 'length' => $len];
    $slot[$eid]['_seg_names'][$seg] = $segName;
    $$bucket = $slot;
}

$standardOut = build_entities($standard, $entById);
$customOut   = build_entities($custom, $entById);

// 注意：不再单独产出实体文件。实体的 code/name/module 已内嵌在字段文件的每个实体块里，
// 且你提供的原始导出（实体 + 完整字段转储）绝不能提交——见 .gitignore 的 /.docs 规则。
write_json("$outDir/kingdee_field.standard.json", $standardOut);
write_json("$outDir/kingdee_field.custom.json", $customOut);

// ---- 报告 ----
$stdFieldCount  = count_flat($standardOut);
$custFieldCount = count_flat($customOut);

$lines = [];
$lines[] = '# K/3 Cloud metadata — clean export';
$lines[] = '';
$lines[] = 'Generated by `tools/build-metadata.php` from:';
$lines[] = "- entities: `$inEntity`";
$lines[] = "- fields:   `$inField`";
$lines[] = '';
$lines[] = '## Summary';
$lines[] = '';
$lines[] = '| metric | value |';
$lines[] = '|---|---|';
$lines[] = '| entities (source) | ' . count($entities) . ' |';
$lines[] = '| fields (source rows) | ' . count($fields) . ' |';
$lines[] = '| standard fields (clean) | ' . $stdFieldCount . ' |';
$lines[] = '| custom 二开 fields (split out) | ' . $custFieldCount . ' |';
$lines[] = '| exact duplicates dropped | ' . $dupes . ' |';
$lines[] = '| anomalies (non-letter field keys) | ' . count($anomalies) . ' |';
$lines[] = '';
$lines[] = '## Files (cleaned output only; raw provided exports are git-ignored)';
$lines[] = '- `kingdee_field.standard.json` — standard fields grouped by entity → segment (each block embeds entity_code / entity_name / module).';
$lines[] = '- `kingdee_field.custom.json` — 二开 fields grouped the same way (kept for review, never deleted).';
$lines[] = '';
$lines[] = '## Classification rule';
$lines[] = '';
$lines[] = 'A field is **custom** iff `kingdee_name` matches `^F_[A-Za-z0-9]{2,4}_`';
$lines[] = '(e.g. `F_PAEZ_lixi`, `F_PEYC_Decimal`). Standard sub-fields that merely';
$lines[] = 'contain `_` (`FBillAmount_LC`, `FEntity_Link_FFlowId`, `FEntity_FENTRYID`,';
$lines[] = '`FMaterialID_Sal`) are **kept as standard**.';
$lines[] = '';
if ($seenCustomCodes !== []) {
    arsort($seenCustomCodes);
    $lines[] = '## Detected 二开 business-group codes (please confirm these are yours)';
    $lines[] = '';
    foreach ($seenCustomCodes as $code => $n) {
        $lines[] = "- `F_{$code}_*` — {$n} field(s)";
    }
    $lines[] = '';
}
if ($unknownEntityRefs !== []) {
    $lines[] = '## WARNING: fields referencing unknown entity ids';
    foreach ($unknownEntityRefs as $eid => $n) {
        $lines[] = "- entity_id $eid → $n field(s)";
    }
    $lines[] = '';
}
if ($anomalies !== []) {
    $lines[] = '## Anomalous field keys (review)';
    foreach (array_slice($anomalies, 0, 50) as $a) {
        $lines[] = "- entity_id {$a['entity_id']}: `" . ($a['name'] === '' ? '(empty)' : $a['name']) . '`';
    }
    $lines[] = '';
}
$lines[] = '## Per-entity field counts (standard / custom)';
$lines[] = '';
$lines[] = '| entity_code | entity_name | standard | custom |';
$lines[] = '|---|---|---:|---:|';
$stdByCode = array_column($standardOut, null, 'entity_code');
$cusByCode = array_column($customOut, null, 'entity_code');
foreach ($entities as $e) {
    $code = $e['entity_code'];
    $s = count_fields($stdByCode[$code] ?? []);
    $c = count_fields($cusByCode[$code] ?? []);
    $lines[] = "| {$code} | {$e['entity_name']} | $s | $c |";
}

file_put_contents("$outDir/kingdee_metadata_report.md", implode("\n", $lines) . "\n");

/* ---------------- 可选：类脚手架 ---------------- */

$scaffoldFiles = 0;
if ($scaffold) {
    if (!is_dir($scaffoldOut) && !mkdir($scaffoldOut, 0777, true) && !is_dir($scaffoldOut)) {
        fwrite(STDERR, "cannot create scaffold dir: $scaffoldOut\n");
        exit(1);
    }

    $blocks = $withCustom ? merge_blocks($standardOut, $customOut) : $standardOut;

    $map = [];
    $usedClass = [];
    foreach ($blocks as $b) {
        $cls = studly((string) $b['entity_code']);
        if (isset($usedClass[$cls])) {
            $usedClass[$cls]++;
            $cls .= (string) $usedClass[$cls];
        } else {
            $usedClass[$cls] = 1;
        }

        file_put_contents("$scaffoldOut/$cls.php", render_entity_class($b, $cls, $scaffoldNs));
        $map[(string) $b['entity_code']] = $scaffoldNs . '\\' . $cls;
        $scaffoldFiles++;
    }

    $rows = [];
    foreach ($map as $code => $fqcn) {
        $rows[] = '    ' . var_export($code, true) . ' => ' . var_export($fqcn, true) . ',';
    }
    file_put_contents(
        "$scaffoldOut/map.php",
        "<?php\n\ndeclare(strict_types=1);\n\n"
        . "/** entity_code => 生成的类 FQCN。把它们逐条喂给 Entity::register(\$code, \$class)。 */\n"
        . "return [\n" . implode("\n", $rows) . "\n];\n"
    );
}

echo "OK\n";
echo "entities=" . count($entities)
    . " standard=$stdFieldCount custom=$custFieldCount dupes=$dupes anomalies=" . count($anomalies) . "\n";
echo "wrote:\n  $outDir/kingdee_field.standard.json\n  $outDir/kingdee_field.custom.json\n  $outDir/kingdee_metadata_report.md\n";
if ($scaffold) {
    echo "  scaffold: $scaffoldFiles class(es) + map.php  ->  $scaffoldOut"
        . ($withCustom ? "  (with 二开 constants)" : '') . "\n";
}

/* ---------------- 辅助函数 ---------------- */

function read_json(string $path): array
{
    if (!is_file($path)) {
        fwrite(STDERR, "input not found: $path\n");
        exit(1);
    }
    $data = json_decode((string) file_get_contents($path), true);
    if (!is_array($data)) {
        fwrite(STDERR, "invalid JSON: $path\n");
        exit(1);
    }
    return $data;
}

function write_json(string $path, mixed $data): void
{
    file_put_contents($path, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n");
}

/** 把 index[entity_id] 转成按实体排序、带分段的实体块列表。 */
function build_entities(array $index, array $entById): array
{
    $out = [];
    foreach ($index as $eid => $segs) {
        $segNames = $segs['_seg_names'] ?? [];
        unset($segs['_seg_names']);
        $segments = [];
        foreach ($segs as $code => $fields) {
            $list = array_values($fields);
            usort($list, static fn ($a, $b) => strcmp($a['key'], $b['key']));
            $segments[] = [
                'code'   => $code,
                'name'   => $segNames[$code] ?? '',
                'fields' => $list,
            ];
        }
        usort($segments, static fn ($a, $b) => strcmp($a['code'], $b['code']));
        $ent = $entById[$eid] ?? [];
        $out[] = [
            'entity_id'   => $eid,
            'entity_code' => $ent['entity_code'] ?? ('UNKNOWN_' . $eid),
            'entity_name' => $ent['entity_name'] ?? '',
            'module'      => $ent['entity_description'] ?? '',
            'segments'    => $segments,
        ];
    }
    usort($out, static fn ($a, $b) => strcmp($a['entity_code'], $b['entity_code']));
    return $out;
}

function count_fields(array $entityBlock): int
{
    $n = 0;
    foreach ($entityBlock['segments'] ?? [] as $seg) {
        $n += count($seg['fields']);
    }
    return $n;
}

function count_flat(array $entityBlocks): int
{
    $n = 0;
    foreach ($entityBlocks as $b) {
        $n += count_fields($b);
    }
    return $n;
}

/** SAL_SaleOrder -> SalSaleorder（起始命名；开发者可随意改名）。 */
function studly(string $code): string
{
    $parts = preg_split('/[^A-Za-z0-9]+/', $code, -1, PREG_SPLIT_NO_EMPTY) ?: [];
    $out = '';
    foreach ($parts as $p) {
        $out .= ucfirst(strtolower($p));
    }

    return $out !== '' ? $out : 'Entity';
}

/** FCustId / FBUSINESSDEPTID.FName -> FLD_FCUSTID / FLD_FBUSINESSDEPTID_FNAME。 */
function const_name(string $key): string
{
    return 'FLD_' . strtoupper(preg_replace('/[^A-Za-z0-9]/', '_', $key) ?? '');
}

/** 把二开（自定义）字段按实体 + 分段折入标准块。 */
function merge_blocks(array $std, array $cus): array
{
    $byId = [];
    foreach ($std as $i => $b) {
        $byId[$b['entity_id']] = $i;
    }

    foreach ($cus as $cb) {
        if (!isset($byId[$cb['entity_id']])) {
            continue;
        }
        $idx = $byId[$cb['entity_id']];
        $target = $std[$idx];

        foreach ($cb['segments'] as $cseg) {
            $found = null;
            foreach ($target['segments'] as $j => $sseg) {
                if ($sseg['code'] === $cseg['code']) {
                    $found = $j;
                    break;
                }
            }
            if ($found === null) {
                $target['segments'][] = $cseg;
                continue;
            }
            $have = [];
            foreach ($target['segments'][$found]['fields'] as $f) {
                $have[$f['key']] = true;
            }
            foreach ($cseg['fields'] as $f) {
                if (!isset($have[$f['key']])) {
                    $target['segments'][$found]['fields'][] = $f;
                }
            }
            usort($target['segments'][$found]['fields'], static fn ($a, $b) => strcmp($a['key'], $b['key']));
        }
        usort($target['segments'], static fn ($a, $b) => strcmp($a['code'], $b['code']));
        $std[$idx] = $target;
    }

    return $std;
}

/** 为一个实体块渲染一个可编辑的脚手架类。 */
function render_entity_class(array $block, string $class, string $namespace): string
{
    $code = (string) $block['entity_code'];
    $name = (string) ($block['entity_name'] ?? '');
    $module = (string) ($block['module'] ?? '');

    $out = "<?php\n\ndeclare(strict_types=1);\n\n";
    $out .= "namespace $namespace;\n\n";
    $out .= "use K3Cloud\\Entity;\n\n";
    $out .= "/**\n";
    $out .= " * " . ($name !== '' ? "$name " : '') . "($code)" . ($module !== '' ? " — $module" : '') . ".\n";
    $out .= " *\n";
    $out .= " * 由 K/3 Cloud 元数据生成的脚手架——拷进你的工程后可自由编辑。\n";
    $out .= " * 下面的常量/helper 只是为补全提供便利，并非白名单：\n";
    $out .= " * 其它任意字段（含二开）仍可通过 ->set()/->custom()/->package()/->line() 使用。\n";
    $out .= " */\n";
    $out .= "final class $class extends Entity\n{\n";
    $out .= "    public const FORM_ID = " . var_export($code, true) . ";\n";

    $usedConst = [];
    $entrySegments = [];

    foreach ($block['segments'] as $seg) {
        $scode = (string) $seg['code'];
        if (($seg['fields'] ?? []) === []) {
            continue;
        }
        $out .= "\n    // " . (($seg['name'] ?? '') !== '' ? $seg['name'] : $scode) . "  [$scode]\n";
        foreach ($seg['fields'] as $f) {
            $cn = const_name((string) $f['key']);
            if (isset($usedConst[$cn])) {
                $usedConst[$cn]++;
                $cn .= '__' . $usedConst[$cn];
            } else {
                $usedConst[$cn] = 1;
            }
            $line = "    public const $cn = " . var_export((string) $f['key'], true) . ";";
            $title = str_replace(["\r", "\n", "*/"], ' ', (string) ($f['title'] ?? ''));
            if ($title !== '') {
                $line .= "  // " . $title;
            }
            $out .= $line . "\n";
        }
        if ($scode !== 'FBillHead' && $scode !== '(unsegmented)') {
            $entrySegments[] = $scode;
        }
    }

    $seenMethod = [];
    foreach ($entrySegments as $scode) {
        $method = 'add' . studly($scode) . 'Line';
        if (isset($seenMethod[$method])) {
            continue;
        }
        $seenMethod[$method] = true;
        $out .= "\n    public function $method(callable|array \$row): static\n";
        $out .= "    {\n        return \$this->line(" . var_export($scode, true) . ", \$row);\n    }\n";
    }

    $out .= "}\n";

    return $out;
}
